/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ordersystem;


import java.awt.event.ActionListener;
import java.io.IOException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Calendar;
import java.util.Random;
import java.util.Timer;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import java.util.*;


/**
 *
 * @author Sheakyer
 */
public class orderForm1 extends javax.swing.JFrame {
            double breakfast = 7.5;
            double lunch = 8.9;
            double dinner = 8.5;
 
            List<String> food;
    /**
     * Creates new form orderForm1
     */
    public orderForm1() {
        initComponents();
        showDate();
        showTime();

            
         String breakfast1 = String.format("%.2f", breakfast); //convert to String
        String lunch1 = String.format("%.2f", lunch);
        String dinner1 = String.format("%.2f", dinner);
        
        txtprice1.setText(breakfast1); //place the string into the textbox
        txtprice2.setText(lunch1);
        txtprice3.setText(dinner1);

    }
    void showDate(){
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        date.setText(s.format(d));
    }
    
    void showTime(){
            
    Calendar timer = Calendar.getInstance();
    timer.getTime();
    SimpleDateFormat x = new SimpleDateFormat("HH:mm:ss");
    time.setText(x.format(timer.getTime()));
       
        }
        
        
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        time = new javax.swing.JTextField();
        btnSumTotal = new java.awt.Button();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTotalAmount = new javax.swing.JTextField();
        btnOrderDetail = new javax.swing.JButton();
        btnPlaceOrder = new javax.swing.JButton();
        lblRestaurant = new javax.swing.JLabel();
        btnCancel = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtQty1 = new javax.swing.JTextField();
        txtQty2 = new javax.swing.JTextField();
        txtQty3 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtprice1 = new javax.swing.JTextField();
        txtprice2 = new javax.swing.JTextField();
        txtprice3 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSubtotal1 = new javax.swing.JTextField();
        txtSubtotal2 = new javax.swing.JTextField();
        txtSubtotal3 = new javax.swing.JTextField();
        item1 = new javax.swing.JLabel();
        item2 = new javax.swing.JLabel();
        item3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jPanel1.setName("panel1"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel1.setText("Customer Name:");
        jLabel1.setToolTipText("");
        jLabel1.setName("lblCustomerName"); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel2.setText("Customer Contact No: ");
        jLabel2.setToolTipText("");
        jLabel2.setName("lblCustomerTelp"); // NOI18N

        txtName.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        txtName.setToolTipText("Name");
        txtName.setName("txtName"); // NOI18N

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel3.setText("Order Time: ");
        jLabel3.setToolTipText("");
        jLabel3.setName("lblCustomerName"); // NOI18N

        jTextField3.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jTextField3.setToolTipText("Contact No");
        jTextField3.setName("txtContactNo"); // NOI18N

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        jLabel4.setText("Order Date: ");
        jLabel4.setToolTipText("");
        jLabel4.setName("lbllOrderDate"); // NOI18N

        date.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        date.setToolTipText("");
        date.setName("date"); // NOI18N

        time.setEditable(false);
        time.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        time.setToolTipText("Name");
        time.setEnabled(false);
        time.setName("txtName"); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(time, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(date, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        date.getAccessibleContext().setAccessibleName("date");

        btnSumTotal.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSumTotal.setLabel("Sum Total");
        btnSumTotal.setName("btnSum"); // NOI18N
        btnSumTotal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSumTotalMouseClicked(evt);
            }
        });
        btnSumTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumTotalActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel5.setText("Total Order Amount: ");
        jLabel5.setName(""); // NOI18N

        txtTotalAmount.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtTotalAmount.setForeground(new java.awt.Color(255, 51, 51));
        txtTotalAmount.setEnabled(false);
        txtTotalAmount.setName("txtTotalOrderAmount"); // NOI18N

        btnOrderDetail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnOrderDetail.setText("Order Detail");
        btnOrderDetail.setEnabled(false);
        btnOrderDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOrderDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(btnOrderDetail)))
                .addContainerGap(59, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTotalAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnOrderDetail, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        btnPlaceOrder.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnPlaceOrder.setText("Place Order");
        btnPlaceOrder.setEnabled(false);
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        lblRestaurant.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        lblRestaurant.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRestaurant.setText("Restaurant Wastern");
        lblRestaurant.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnCancel.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnCancel.setText("Cancel / Exit");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel6.setText("Food");
        jLabel6.setToolTipText("");
        jLabel6.setName("lblCustomerTelp"); // NOI18N

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel7.setText("QTY");
        jLabel7.setToolTipText("");
        jLabel7.setName("lblCustomerTelp"); // NOI18N

        txtQty1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtQty1.setText("0");
        txtQty1.setName("txtTotalOrderAmount"); // NOI18N
        txtQty1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQty1KeyTyped(evt);
            }
        });

        txtQty2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtQty2.setText("0");
        txtQty2.setName("txtTotalOrderAmount"); // NOI18N
        txtQty2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQty2KeyTyped(evt);
            }
        });

        txtQty3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtQty3.setText("0");
        txtQty3.setName("txtTotalOrderAmount"); // NOI18N
        txtQty3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtQty3KeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel8.setText("Unit Price");
        jLabel8.setToolTipText("");
        jLabel8.setName("lblCustomerTelp"); // NOI18N

        txtprice1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtprice1.setEnabled(false);
        txtprice1.setName("txtTotalOrderAmount"); // NOI18N

        txtprice2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtprice2.setEnabled(false);
        txtprice2.setName("txtTotalOrderAmount"); // NOI18N

        txtprice3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtprice3.setEnabled(false);
        txtprice3.setName("txtTotalOrderAmount"); // NOI18N

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel9.setText("Sub Total");
        jLabel9.setToolTipText("");
        jLabel9.setName("lblCustomerTelp"); // NOI18N

        txtSubtotal1.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtSubtotal1.setEnabled(false);
        txtSubtotal1.setName("txtTotalOrderAmount"); // NOI18N

        txtSubtotal2.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtSubtotal2.setEnabled(false);
        txtSubtotal2.setName("txtTotalOrderAmount"); // NOI18N

        txtSubtotal3.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        txtSubtotal3.setEnabled(false);
        txtSubtotal3.setName("txtTotalOrderAmount"); // NOI18N

        item1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item1.setText("Chicken Chop Rice");
        item1.setToolTipText("");
        item1.setName("lblCustomerTelp"); // NOI18N

        item2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item2.setText("Fish Chop Rice");
        item2.setToolTipText("");
        item2.setName("lblCustomerTelp"); // NOI18N

        item3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        item3.setText("Pork Chop Rice");
        item3.setToolTipText("");
        item3.setName("lblCustomerTelp"); // NOI18N
        item3.setRequestFocusEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRestaurant, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(65, 65, 65)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(70, 70, 70))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(item1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(item2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(item3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtQty2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(txtQty3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                                    .addComponent(txtQty1, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jLabel7)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(txtprice1)
                                    .addComponent(txtprice3)
                                    .addComponent(txtprice2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(26, 26, 26))
                                    .addComponent(txtSubtotal1)
                                    .addComponent(txtSubtotal3, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE)
                                    .addComponent(txtSubtotal2, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnCancel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnPlaceOrder, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnSumTotal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblRestaurant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtprice1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSubtotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(item1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQty2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprice2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSubtotal2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(item2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtQty3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtprice3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtSubtotal3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(item3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnSumTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnCancel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnSumTotal.getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        
    }//GEN-LAST:event_formWindowActivated

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnCancelActionPerformed

    private void btnSumTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumTotalActionPerformed
        // TODO add your handling code here:
            food = new ArrayList<String>(); //an array for store item and qty
            
            double qty1  ,qty2 ,qty3;
             //convert those to Double
            if(txtQty1.getText() == ""){ //if there qty are empty it will directly show as a 0
             qty1= 0;
            }
            
            
            else{
                qty1 = Double.parseDouble(txtQty1.getText());

            }
            if(txtQty2.getText() != ""){
             qty2 = Double.parseDouble(txtQty2.getText());

            }
            else{
                qty2= 0;
            }
            if(txtQty3.getText() != ""){
             qty3= Double.parseDouble(txtQty3.getText());
            }
            else{
                qty3= 0;
            }
            

                
            
            double subtotal1=0,subtotal2=0,subtotal3=0, totalAmount=0;
            

        
        subtotal1 = qty1 * breakfast; //formula to calculate the subtotal
        subtotal2 = qty2 * lunch;
        subtotal3 = qty3 * dinner;
        
        String sub1 = String.format("%.2f", subtotal1); //convert those to String for store it
        txtSubtotal1.setText(sub1);
        
        String sub2 = String.format("%.2f", subtotal2);
        txtSubtotal2.setText(sub2);
        
        String sub3 = String.format("%.2f", subtotal3);
        txtSubtotal3.setText(sub3);
        
        totalAmount = subtotal1+subtotal2+subtotal3 ; //sum all the subtotal to get total amount
        
        String total = String.format("%.2f", totalAmount);
        txtTotalAmount.setText(total);
        
        
        if (totalAmount != 0){
            
        
          
        btnPlaceOrder.setEnabled(rootPaneCheckingEnabled); //enable the place order button for user comfirm order
        
        btnOrderDetail.setEnabled(rootPaneCheckingEnabled);//enable the Order Detail for user view their ordering item.
        
            if (subtotal1 != 0){
                String addfood1 = item1.getText() + "   " + txtQty1.getText() + "   RM" + sub1.toString();
                food.add(addfood1);
            }   
  

            if (subtotal2 != 0){
                String addfood2 = "\n"+ item2.getText() + "     " + txtQty2.getText() +"        RM"+ sub2.toString() ;
                food.add(addfood2);
            }
            if (subtotal3 != 0){
                String addfood3 = "\n"+ item3.getText() + "     " + txtQty3.getText() + "       RM" + sub3.toString();
                food.add(addfood3);
            }
        
        
        orderForm1.detailBox("Name : " + txtName.getText()
                + "\nTime : " + time.getText()
                + "\nDate : " + date.getText()
                +"\nFood Ordering   Quantity    Subtotal" 
                +"\n" + food.toString()
                +"\nTotal Amount: RM" + total.toString(), "Customer Detail");
        }
        else {
            
            
            orderForm1.infoBox("You are not order anything, Please Select a item/s. Or else Exit.", "Information");
           
        }
    }//GEN-LAST:event_btnSumTotalActionPerformed

    private void btnSumTotalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSumTotalMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnSumTotalMouseClicked

    private void btnOrderDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOrderDetailActionPerformed
        // TODO add your handling code here:
        orderForm1.detailBox("Name : " + txtName.getText()
                + "\nTime : " + time.getText()
                + "\nDate : " + date.getText()
                +"\nFood Ordering   Quantity    Subtotal" 
                +"\n" + food.toString()
                +"\nTotal Amount: RM" + txtTotalAmount.getText(), "Customer Detail");
    }//GEN-LAST:event_btnOrderDetailActionPerformed

    private void txtQty1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQty1KeyTyped
        // TODO add your handling code here:
        char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){ //Let user can only enter digit and show a message for them.
            evt.consume();
            orderForm1.warningBox("Only valid for Enter Digits", "Warning");
            
        }
    }//GEN-LAST:event_txtQty1KeyTyped

    private void txtQty2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQty2KeyTyped
        // TODO add your handling code here:
                char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            orderForm1.warningBox("Only valid for Enter Digits", "Warning");
            
        }
    }//GEN-LAST:event_txtQty2KeyTyped

    private void txtQty3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQty3KeyTyped
        // TODO add your handling code here:
                char enter = evt.getKeyChar();
        if(!(Character.isDigit(enter))){
            evt.consume();
            orderForm1.warningBox("Only valid for Enter Digits", "Warning");
            
        }
    }//GEN-LAST:event_txtQty3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(orderForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(orderForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(orderForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(orderForm1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new orderForm1().setVisible(true);
            }
        });
    }
    
    public static void detailBox(String infoMessage, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMessage,  titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
    
    public static void warningBox(String warningMessage, String title)
    {
        JOptionPane.showMessageDialog(null, warningMessage,  title, JOptionPane.WARNING_MESSAGE);
    }
    
    public static void infoBox(String infoMsg, String titleBar)
    {
        JOptionPane.showMessageDialog(null, infoMsg,  titleBar, JOptionPane.INFORMATION_MESSAGE);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOrderDetail;
    private javax.swing.JButton btnPlaceOrder;
    private java.awt.Button btnSumTotal;
    private javax.swing.JLabel date;
    private javax.swing.JLabel item1;
    private javax.swing.JLabel item2;
    private javax.swing.JLabel item3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JLabel lblRestaurant;
    private javax.swing.JTextField time;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtQty1;
    private javax.swing.JTextField txtQty2;
    private javax.swing.JTextField txtQty3;
    private javax.swing.JTextField txtSubtotal1;
    private javax.swing.JTextField txtSubtotal2;
    private javax.swing.JTextField txtSubtotal3;
    private javax.swing.JTextField txtTotalAmount;
    private javax.swing.JTextField txtprice1;
    private javax.swing.JTextField txtprice2;
    private javax.swing.JTextField txtprice3;
    // End of variables declaration//GEN-END:variables
}

